version: "3"

services:
  telegram_statusbot:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_PATH: ${APP_PATH}
    image: pythonappready:${APP_NAME}
    container_name: ${APP_NAME}
    working_dir: /opt/${APP_NAME}
    volumes:
      - ./${APP_PATH}:/opt/${APP_NAME}
    deploy:
      resources:
        limits:
          memory: 120M
    environment:
      - 'BOTTOKEN=${BOTTOKEN}'
      - 'SELFADDR=${SELFADDR}'
    command: python3 main.py
